version: 2

sources:
  - name: staging
    database: durable-sunspot-392411
    schema: dbt_database
    tables: 
      - name: ghdata_rm_duplicates

models:
  - name: daily_events
    description: "Daily number of events"

  - name: daily_active_users_push
    description: "Daily number of user activity"